### ISSUE TITLE
Icons not disappearing in time

### ISSUE THREAD

**Issue by Alexey25322** [atar13/Vaon#14]
Hello, I attached a video where you can see the issue.

https://user-images.githubusercontent.com/43210019/124281408-f980de80-db49-11eb-97ca-8d460cd821cf.MP4

**Comment by atar13** [comment]
Thanks for bringing this to my attention. I noticed this issue a while back but I never got the chance to address it. 

Version 1.0.4 should resolve this. It's just been pushed to my repo. Try it out and let me know if the issue still persists.

**Comment by Alexey25322** [comment]
> 
> 
> Thanks for bringing this to my attention. I noticed this issue a while back but I never got the chance to address it.
> 
> Version 1.0.4 should resolve this. It's just been pushed to my repo. Try it out and let me know if the issue still persists.

Hey, thankl you for the quick fix. It works well now.
