### ISSUE TITLE
Icons interference

### ISSUE THREAD

**Issue by Ponnyup** [atar13/Vaon#21]
Can the battery display be movable?
![AA5728BC-3C39-45D6-B32D-3665259B8A9E](https://user-images.githubusercontent.com/34940837/148569424-9eeb302c-4b4f-4438-a01b-43e32376b712.jpeg)
![1C7B0C71-6FDC-40E3-A687-F489F66971E0](https://user-images.githubusercontent.com/34940837/148569430-43cbef3c-88e0-4317-bb86-f204df6d9501.png)

**Comment by atar13** [comment]
Option already exists in preferences.
